version: '3.8'

services:
  db:
    build: ./data
    image: postgres:15
    container_name: postgres_pgvector
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data/init-scripts:/docker-entrypoint-initdb.d  # Correct path to the init-scripts
    networks:
      - translation
    ports:
      - "5432:5432"

  # frontend:
  #   build: ./
  #   working_dir: /app
  #   volumes:
  #     - ./frontend/package.json:/app/package.json
  #     - ./frontend/node_modules:/app/node_modules
  #     - ./frontend/.next:/app/.next
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://backend:8000
  #   command: ["npm", "start"]

  # backend:
  #   build: ./api
  #   ports:
  #     - "8000:8000"
volumes:
  pg_data:

networks:
  translation:
    driver: bridge